name: CI
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: |
          yarn --frozen-lockfile
      - run: |
          npm run format:check
      - env:
          CI: true
        run: |
          npm run test -- --coverage
