name: CI
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: |
          yarn --frozen-lockfile
      - run: |
          npm run format:check
      - env:
          CI: true
        run: |
          npm run test -- --coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: |
          npm run build
      # - name: Deploy to Staging
      #   if: github.event_name == 'push'
      #   env:
      #     SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      #     SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      #   run: |
      #     npx surge --project ./build --domain ${{ secrets.DEPLOY_URL }}
