name: Notify on Release
on:
  release:
    types:
      - published

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Message
        run: |
          echo 'Slack Message'
          # # TODO: docker://technosophos/slack-notify を使用
          # curl -X POST -H 'Content-type: application/json' --data '{"text": "message"}' ${{ secrets.SLACK_WEBHOOK }}
